/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

Tables Used:
    - gold.dim_customers
    - gold.dim_product
    - gold.fact_sales
===============================================================================
*/

-- Find total customers by countries
select
country,
count(customer_key) as 'total_custoemr'
FROM gold.dim_customers
GROUP BY country
ORDER BY total_custoemr DESC ;


-- Find total customers by gender
SELECT
gender,
count(customer_key) as `total_customer`
from gold.dim_customers
GROUP BY gender;


-- Find total products by category
SELECT
category,
count(product_name) as `total_customer`
from gold.dim_product
GROUP BY category
ORDER BY `total_customer` desc;


-- Data correction: fix incorrect product cost for two mislabeled SKUs
select * from silver.crm_prd_info ;
update silver.crm_prd_info
set prd_cost = 869 where prd_nm  IN ('HL Road Frame - Red- 58','HL Road Frame - Black- 58') ;


-- What is the average cost in each category?
SELECT
category,
avg(cost) as `average_cost`
from gold.dim_product
GROUP BY category	
ORDER BY average_cost desc;

-- What is the total revenue generated for each category?
SELECT
p.category as `category`,
sum(s.sales_amount) as `total_sales`
FROM gold.fact_sales as s
LEFT JOIN gold.dim_product as p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY `total_sales` DESC ;


-- What is the total revenue generated by each customer?
SELECT
c.customer_key as `customer_key`,
c.first_name as `first_name`,
c.last_name as `last_name`,
sum(s.sales_amount) as `total_sales`
FROM gold.fact_sales as s
LEFT JOIN gold.dim_customers as c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY `total_sales` DESC ;


-- What is the distribution of sold items across countries?
SELECT
c.country as `country`,
sum(quantity) as `total_sold_items`
FROM gold.fact_sales as s
LEFT JOIN gold.dim_customers as c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY `total_sold_items` DESC ;
